services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO-INITDB_ROOT_USERNAME=admin
      - MONGO-INITDB_ROOT_PASSWORD=pass
  model-controller:
    build: ./api
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  front-end:
    build: ./front-end
    ports:
      - 3000:3000
      