services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO-INITDB_ROOT_USERNAME=admin
      - MONGO-INITDB_ROOT_PASSWORD=pass
  # mongo-express: # CAN BE REMOVED LATER
  #   image: mongo-express
  #   ports: 
  #     - 8080:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #   depends_on:
  #     - mongodb



  # model-controller:
  #   build: ./model_controller
  #   ports:
  #     - 8000:8000
  #  depends_on:
  #     - mongodb
      